const certifications = [
  {
    "name": "Build Your Own Dynamic Web Application",
    "description": "Certified in dynamic web application development, covering foundational JavaScript to advanced full-stack techniques, with hands-on project experience.",
    "logo": "./logo/Nxtwave.svg",
    "certificateImg": "",
    "credentialLink": "https://certificates.ccbp.in/academy/dynamic-web-application?id=CKWGFEGIXW",
    "platforms": ["NxtWave"],
    "language": ["JavaScript", "HTML", "CSS"],
    "category": "Course",
    "completionYear": "March 2024",
  },
  {
    "name": "Generative AI Fundamentals",
    "description": "Certified in Generative AI Fundamentals, covering AI, Machine Learning, Deep Learning, and Data Science basics with insights into generative models.",
    "logo": "./logo/Prodapt-logo.jpg",
    "certificateImg": "./images/Certifications/GenerativeAI-Prodapt.webp",
    "credentialLink": "",
    "platforms": ["Prodapt"],
    "language": ["JavaScript", "HTML", "CSS", "Python"],
    "category": "Course",
    "completionYear": "February 2025",
  },
  {
    "name": "Genik Technologies Pvt Ltd",
    "description": "Certified for successfully completing a full-stack development internship, contributing to the development of Rearticle – a no-code LaTeX typesetting platform for academic writing.",
    "logo": "./logo/Genik.webp",
    "certificateImg": "./images/Certifications/GenikInternship.webp",
    "credentialLink": "",
    "platforms": ["Offline"],
    "language": ["React", "Tailwind CSS", "Firebase", "Radix UI", "Bitbucket"],
    "category": "Internship",
    "completionYear": "April 2024",
  },
  {
    "name": "IEEE Xtreme Programming",
    "description": "Participation in the IEEE Xtreme Programming competition, showcasing problem-solving skills and coding proficiency in a global coding challenge.",
    "logo": "./logo/ieee.png",
    "certificateImg": "./images/Certifications/IEEE/IEEEXtreme.webp",
    "credentialLink": "",
    "platforms": ["IEEE"],
    "language": ["JavaScript", "HTML", "CSS", "Node.js"],
    "category": "Competition",
    "completionYear": "October 2023",
  },
  {
    "name": "Game Of Threads",
    "description": "Participation in the Game of Threads competition, demonstrating skills in coding through a series of challenges.",
    "logo": "./logo/SairamEng.webp",
    "certificateImg": "./images/Certifications/Competetion/GameOfThreads.jpg",
    "credentialLink": "",
    "platforms": ["Sairam Engineering College"],
    "language": ["C", "Python"],
    "category": "Competition",
    "completionYear": "November 2023",
  },
  {
    "name": "Learnathon 2022",
    "description": "Participated in Learnathon 2022 by completing courses across platforms like Microsoft, Bentley, AWS, Celonis, and others, gaining knowledge in diverse domains.",
    "logo": "./logo/Ictacademy.png",
    "certificateImg": "./images/Certifications/Learnathon/Learnathon1.webp",
    "credentialLink": "",
    "platforms": ["Microsoft", "Bentley", "AWS", "Celonis", "ICT Academy", "MathWorks", "VMware"],
    "language": ["JavaScript", "HTML", "CSS", "Python", "Automation", "AI"],
    "category": "Course",
    "completionYear": "October 2022",
  },
  {
    "name": "Build Your Own Static Website",
    "description": "Certified in building static websites using HTML, CSS, and Bootstrap, with a focus on mobile-first responsive design.",
    "logo": "./logo/Nxtwave.svg",
    "certificateImg": "",
    "credentialLink": "https://certificates.ccbp.in/academy/static-website?id=JZBGHEBOGG",
    "platforms": ["NxtWave"],
    "language": ["HTML", "CSS", "Bootstrap"],
    "category": "Course",
    "completionYear": "August 2023"
  },
  {
    "name": "Programming Foundations",
    "description": "Certified in Python programming fundamentals with over 500+ problems solved, mastering key programming concepts.",
    "logo": "./logo/Nxtwave.svg",
    "certificateImg": "",
    "credentialLink": "https://certificates.ccbp.in/academy/programming-foundations-with-python?id=MYJWHVZXSR",
    "platforms": ["NxtWave"],
    "language": ["Python"],
    "category": "Course",
    "completionYear": "December 2023"
  },
  {
    "name": "Build Your Own Responsive Website",
    "description": "Certified in creating responsive websites using HTML, CSS, and Bootstrap, applying grid systems and media queries.",
    "logo": "./logo/Nxtwave.svg",
    "certificateImg": "",
    "credentialLink": "https://certificates.ccbp.in/academy/build-your-own-responsive-website?id=KJLVJHVSHI",
    "platforms": ["NxtWave"],
    "language": ["HTML", "CSS", "Bootstrap"],
    "category": "Course",
    "completionYear": "November 2023"
  },
  {
    "name": "Introduction to Databases",
    "description": "Certified in database fundamentals and querying using SQL, with insights into MongoDB.",
    "logo": "./logo/Nxtwave.svg",
    "certificateImg": "",
    "credentialLink": "https://certificates.ccbp.in/academy/introduction-to-databases?id=HUVIHZAMFS",
    "platforms": ["NxtWave"],
    "language": ["SQL", "MongoDB"],
    "category": "Course",
    "completionYear": "April 2024"
  },
  {
  name: "Microsoft Azure AI Fundamentals: Generative AI",
  description: "Microsoft Certified Azure AI Fundamentals (AI‑900): foundational knowledge in AI concepts, machine learning, computer vision, NLP, and generative AI workloads on Azure.",
  logo: "./logo/Microsoft.svg", 
  certificateImg: "", 
  credentialLink: "https://learn.microsoft.com/api/achievements/share/en-us/NareshBA-5244/8ZYS7XTW?sharingId=AB6A47135F07E371",
  platforms: ["Microsoft"],
  language: ["English"],
  category: "Certification",
  completionYear: "April 2025"
},
  {
    "name": "JavaScript Essentials",
    "description": "Certified in core JavaScript concepts including events, scope, hoisting, and asynchronous programming.",
    "logo": "./logo/Nxtwave.svg",
    "certificateImg": "",
    "credentialLink": "https://certificates.ccbp.in/academy/javascript-essentials?id=DNJFLINHXT",
    "platforms": ["NxtWave"],
    "language": ["JavaScript"],
    "category": "Course",
    "completionYear": "April 2024"
  },
  {
    "name": "Responsive Web Design using Flexbox",
    "description": "Certified in designing responsive layouts using CSS Flexbox and media queries for a seamless user experience.",
    "logo": "./logo/Nxtwave.svg",
    "certificateImg": "",
    "credentialLink": "https://certificates.ccbp.in/academy/responsive-web-design-using-flexbox?id=NCIXIGMIXE",
    "platforms": ["NxtWave"],
    "language": ["CSS Flexbox"],
    "category": "Course",
    "completionYear": "May 2024"
  },
  {
    "name": "Developer Foundations",
    "description": "Certified in developer essentials including Git, command-line tools, OS fundamentals, and networking basics.",
    "logo": "./logo/Nxtwave.svg",
    "certificateImg": "",
    "credentialLink": "https://certificates.ccbp.in/academy/developer-foundations?id=KEHRPCBWMZ",
    "platforms": ["NxtWave"],
    "language": ["Git", "Command Line"],
    "category": "Course",
    "completionYear": "June 2024"
  },
  {
  "name": "Microsoft Azure AI Fundamentals: Computer Vision",
  "description": "Microsoft Certified AI-900 specialization in Computer Vision: foundational skills in image classification, object detection, facial recognition, and responsible AI using Azure AI Vision services.",
  "logo": "./logo/Microsoft.svg",
  "certificateImg": "",
  "credentialLink": "https://learn.microsoft.com/api/achievements/share/en-us/NareshBA-5244/XQZGFU8Y?sharingId=AB6A47135F07E371", // Replace with actual link
  "platforms": ["Microsoft"],
  "language": ["English"],
  "category": "Certification",
  "completionYear": "April 2025"
},
  {
    "name": "Node JS",
    "description": "Certified in backend development using Node.js and Express, covering routing, APIs, and database integration.",
    "logo": "./logo/Nxtwave.svg",
    "certificateImg": "",
    "credentialLink": "https://certificates.ccbp.in/academy/node-js?id=XWIPHDPPFM",
    "platforms": ["NxtWave"],
    "language": ["Node.js"],
    "category": "Course",
    "completionYear": "August 2024"
  },
  {
    "name": "React JS - Getting started",
    "description": "Certified in building modern web applications using React JS, with a focus on components, state, and props.",
    "logo": "./logo/Nxtwave.svg",
    "certificateImg": "",
    "credentialLink": "https://certificates.ccbp.in/academy/react-js?id=PJXHJXPBWP",
    "platforms": ["NxtWave"],
    "language": ["React"],
    "category": "Course",
    "completionYear": "October 2024"
  },
  {
  "name": "Microsoft Azure AI Fundamentals: Natural Language Processing",
  "description": "Microsoft Certified AI-900 specialization in Natural Language Processing: foundational knowledge in text analytics, sentiment analysis, translation, and conversational AI using Azure Cognitive Services.",
  "logo": "./logo/Microsoft.svg",
  "certificateImg": "", 
  "credentialLink": "https://learn.microsoft.com/api/achievements/share/en-us/NareshBA-5244/NVALRKAF?sharingId=AB6A47135F07E371", // Replace with actual link
  "platforms": ["Microsoft"],
  "language": ["English"],
  "category": "Certification",
  "completionYear": "April 2025"
},
  {
    "name": "Learnathon 2023",
    "description": "Participated in Learnathon 2023 by completing courses across platforms like Microsoft, Bentley, AWS, Celonis, and others, gaining knowledge in diverse domains.",
    "logo": "./logo/Ictacademy.png",
    "certificateImg": "./images/Certifications/Learnathon/Learnathon2.webp",
    "credentialLink": "",
    "platforms": ["Microsoft", "Bentley", "AWS", "Celonis", "ICT Academy", "MathWorks", "VMware"],
    "language": ["JavaScript", "HTML", "CSS", "Python", "Automation", "AI"],
    "category": "Course",
    "completionYear": "September 2023",
  },
  {
    "name": "Hack O Holic",
    "description": "Participated in the Hack O Holic hackathon, demonstrating coding proficiency and problem-solving skills, and secured a top 20 position.",
    "logo": "./logo/StJoseph.jpg",
    "certificateImg": "./images/Certifications/Competetion/HackOHolic.webp",
    "credentialLink": "",
    "platforms": ["St. Joseph's Institute of Technology"],
    "language": ["AI", "Python", "JavaScript", "HTML", "CSS", "Node.js", "OpenCV", "TensorFlow", "Flask", "Firebase"],
    "category": "Competition",
    "completionYear": "September 2023",
  },
  {
  "name": "Fine-tune a foundation model with Azure Machine Learning",
  "description": "Microsoft Certified: Hands-on experience fine-tuning large foundation models using Azure Machine Learning Studio, pipelines, and prompt engineering to customize model behavior.",
  "logo": "./logo/Microsoft.svg",
  "certificateImg": "", 
  "credentialLink": "https://learn.microsoft.com/api/achievements/share/en-us/NareshBA-5244/JUCL8A4T?sharingId=AB6A47135F07E371", 
  "platforms": ["Microsoft"],
  "language": ["English"],
  "category": "Certification",
  "completionYear": "April 2025"
},
  {
    "name": "Game Of Threads",
    "description": "Participation in the Game of Threads competition, demonstrating skills in coding through a series of challenges.",
    "logo": "./logo/SairamEng.webp",
    "certificateImg": "./images/Certifications/Competetion/GameOfThreads.jpg",
    "credentialLink": "",
    "platforms": ["Sairam Engineering College"],
    "language": ["C", "Python"],
    "category": "Competition",
    "completionYear": "November 2023",
  },
  {
    "name": "Hack Riot",
    "description": "Secured 1st place in the 24-hour Hack Riot hackathon by developing an AR/VR virtual museum, enabling students to explore historical places remotely through immersive technology.",
    "logo": "./logo/SairamEng.webp",
    "certificateImg": "./images/Certifications/Competetion/HackRiot.webp",
    "credentialLink": "",
    "platforms": ["Sairam Engineering College"],
    "language": ["AR/VR", "Python", "HTML", "CSS", "JavaScript"],
    "category": "Competition",
    "completionYear": "April 2023",
  },
  {
    "name": "Starlight Coding",
    "description": "Participation in the Starlight Coding competition, showcasing coding skills and problem-solving abilities in a competitive environment.",
    "logo": "./logo/anna-university.png",
    "certificateImg": "./images/Certifications/Competetion/Starlight-coding-event.webp",
    "credentialLink": "",
    "platforms": ["Anna University"],
    "language": ["C", "Python", "Java"],
    "category": "Competition",
    "completionYear": "March 2024",
  },
  {
  "name": "Understand the Transformer architecture and explore large language models in Azure Machine Learning",
  "description": "Microsoft Certified: Explored the core concepts of Transformer architecture and gained foundational insights into leveraging LLMs with Azure Machine Learning tools and infrastructure.",
  "logo": "./logo/Microsoft.svg",
  "certificateImg": "", 
  "credentialLink": "https://learn.microsoft.com/api/achievements/share/en-us/NareshBA-5244/H7RFVQF8?sharingId=AB6A47135F07E371", // Replace with your shareable link
  "platforms": ["Microsoft"],
  "language": ["English"],
  "category": "Certification",
  "completionYear": "April 2025"
},
  {
    "name": "Design Derbies",
    "description": "Won 1st place in Innovatia 2.0 National Level Symposium by developing a frontend web application during the design and development event, showcasing creativity, UI/UX skills, and rapid prototyping.",
    "logo": "./logo/SairamEng.webp",
    "certificateImg": "./images/Certifications/Competetion/DesignDerbies.jpg",
    "credentialLink": "",
    "platforms": ["Sairam Engineering College"],
    "language": ["HTML", "CSS", "JavaScript", "Git"],
    "category": "Competition",
    "completionYear": "November 2023",
  },
  {
    "name": "AI for Everyone",
    "description": "Certified in IBM AI for Everyone: Master the Basics, gaining foundational knowledge in Artificial Intelligence, its applications, and impact across industries.",
    "logo": "./logo/edx.png",
    "certificateImg": "./images/Certifications/AIforEveryone.jpg",
    "credentialLink": "", 
    "platforms": ["edX", "IBM"],
    "language": ["Python"],
    "category": "Course",
    "completionYear": "July 2021",
  },
  {
    "name": "Deep Learning Fundamentals with Keras",
    "description": "Certified in Deep Learning Fundamentals with Keras by IBM, covering key concepts of neural networks and hands-on model development using Keras.",
    "logo": "./logo/edx.png",
    "certificateImg": "./images/Certifications/DeepLearningFundamentalswithKeras.jpg",
    "credentialLink": "",
    "platforms": ["edX", "IBM"],
    "language": ["Python"],
    "category": "Course",
    "completionYear": "April 2023",
  },
  {
    "name": "Exploring GraphQL: A Query Language for APIs",
    "description": "Certified in Exploring GraphQL by LinuxFoundationX, gaining hands-on experience in designing and querying APIs using GraphQL syntax and schema structure.",
    "logo": "./logo/edx.png",
    "certificateImg": "./images/Certifications/ExploringGraphQL.jpg",
    "credentialLink": "",
    "platforms": ["edX", "Linux Foundation"],
    "language": ["JavaScript"],
    "category": "Course",
    "completionYear": "April 2023",
  },
  {
    "name": "Introduction to Web Development with HTML5, CSS3, and JavaScript",
    "description": "Certified in Web Development by IBM, mastering the basics of HTML5, CSS3, and JavaScript to build responsive and interactive web applications.",
    "logo": "./logo/edx.png",
    "certificateImg": "./images/Certifications/IntroductionToWebDevelopment.jpg",
    "credentialLink": "",
    "platforms": ["edX", "IBM"],
    "language": ["HTML", "CSS", "JavaScript"],
    "category": "Course",
    "completionYear": "April 2023",
  },
  {
    "name": "Python Basics for Data Science",
    "description": "Certified in Python Basics for Data Science by IBM, covering core Python programming concepts and their application in data science workflows.",
    "logo": "./logo/edx.png",
    "certificateImg": "./images/Certifications/PythonBasicsforDataScience.jpg",
    "credentialLink": "",
    "platforms": ["edX", "IBM"],
    "language": ["Python"],
    "category": "Course",
    "completionYear": "July 2021",
  },
  {
    "name": "Front End Development - HTML",
    "description": "Certified in Front End Development - HTML by Great Learning Academy, gaining foundational skills in structuring web content using semantic HTML elements.",
    "logo": "./logo/greatLearning.svg",
    "certificateImg": "./images/Certifications/GreatLearning/FrontendDevelopment-HTML.jpg",
    "credentialLink": "",
    "platforms": ["Great Learning"],
    "language": ["HTML"],
    "category": "Course",
    "completionYear": "April 2023"
  },
  {
    "name": "Front End Development - CSS",
    "description": "Certified in Front End Development - CSS by Great Learning Academy, gaining hands-on knowledge in styling web applications using modern CSS techniques.",
    "logo": "./logo/greatLearning.svg",
    "certificateImg": "./images/Certifications/GreatLearning/FrontendDevelopment-CSS.jpg",
    "credentialLink": "",
    "platforms": ["Great Learning"],
    "language": ["CSS"],
    "category": "Course",
    "completionYear": "April 2023"
  },
  {
    "name": "Introduction to JavaScript",
    "description": "Certified in Introduction to JavaScript by Great Learning Academy, covering foundational JavaScript concepts and scripting for dynamic web interactions.",
    "logo": "./logo/greatLearning.svg",
    "certificateImg": "./images/Certifications/GreatLearning/FrontendDevelopment-Javascript.jpg",
    "credentialLink": "",
    "platforms": ["Great Learning"],
    "language": ["JavaScript"],
    "category": "Course",
    "completionYear": "April 2023"
  },
  {
    "name": "AWS Essentials",
    "description": "Participated in a webinar on AWS Essentials conducted by IEEE BTS at Sri Sairam Institute of Technology, gaining insights into core AWS services and cloud infrastructure fundamentals.",
    "logo": "./logo/ieee.png",
    "certificateImg": "./images/Certifications/IEEE/AwsWebinar.webp",
    "credentialLink": "",
    "platforms": ["IEEE", "Sri Sairam Institute of Technology"],
    "language": ["Cloud Computing"],
    "category": "Webinar",
    "completionYear": "May 2023"
  },
  {
    "name": "Foundations of AI",
    "description": "Successfully completed a 4-week virtual internship on Foundations of AI, initiated by Microsoft, implemented by Edunet Foundation in collaboration with AICTE, gaining hands-on experience in AI fundamentals.",
    "logo": "./logo/EdunetFoundation.png",
    "certificateImg": "./images/Certifications/Internship/EdunetInternshipCertificate.webp",
    "credentialLink": "",
    "platforms": ["Microsoft", "Edunet Foundation", "AICTE"],
    "language": ["AI/ML"],
    "category": "Internship",
    "completionYear": "May 2025"
  },
  {
    "name": "AI Engineering",
    "description": "Completed a 4-week virtual internship program in AI Engineering conducted by ICT Academy and OpenWeaver, including the successful submission of an industry-ready project.",
    "logo": "./logo/Ictacademy.png",
    "certificateImg": "./images/Certifications/Internship/OpenweaverInternship.webp",
    "credentialLink": "",
    "platforms": ["ICT Academy", "OpenWeaver"],
    "language": ["AI/ML"],
    "category": "Internship",
    "completionYear": "October 2023"
  },
  {
    "name": "Java Programming Essentials",
    "description": "Completed a 3-day bootcamp on Java Programming Essentials conducted by LetsUpgrade in collaboration with NSDC and ITM Edutech Training Pvt. Ltd.",
    "logo": "./logo/letsupgrade.webp",
    "certificateImg": "./images/Certifications/LetsUpgrade/Java.webp",
    "credentialLink": "",
    "platforms": ["LetsUpgrade"],
    "language": ["Java"],
    "category": "Bootcamp",
    "completionYear": "July 2023"
  },
  {
    "name": "Javascript Bootcamp",
    "description": "Completed a 5-day Javascript Bootcamp conducted by LetsUpgrade in collaboration with NSDC and ITM Edutech Training Pvt. Ltd.",
    "logo": "./logo/letsupgrade.webp",
    "certificateImg": "./images/Certifications/LetsUpgrade/Javascript.webp",
    "credentialLink": "",
    "platforms": ["LetsUpgrade"],
    "language": ["JavaScript"],
    "category": "Bootcamp",
    "completionYear": "July 2024"
  },
  {
    "name": "Machine Learning using Python Bootcamp",
    "description": "Completed a 5-day Machine Learning using Python Bootcamp conducted by LetsUpgrade in collaboration with NSDC and ITM Edutech Training Pvt. Ltd.",
    "logo": "./logo/letsupgrade.webp",
    "certificateImg": "./images/Certifications/LetsUpgrade/MachineLearning.webp",
    "credentialLink": "",
    "platforms": ["LetsUpgrade"],
    "language": ["Python", "Machine Learning"],
    "category": "Bootcamp",
    "completionYear": "July 2024"
  },
  {
    "name": "Postman API Fundamentals",
    "description": "Completed a 3-day Postman API Fundamentals certification bootcamp conducted by LetsUpgrade in collaboration with NSDC and ITM Edutech Training Pvt. Ltd.",
    "logo": "./logo/letsupgrade.webp",
    "certificateImg": "./images/Certifications/LetsUpgrade/Postman.webp",
    "credentialLink": "",
    "platforms": ["LetsUpgrade"],
    "language": ["API", "Postman"],
    "category": "Bootcamp",
    "completionYear": "July 2023"
  },
  {
    "name": "SQL Essentials Bootcamp",
    "description": "Completed a 3-day SQL Essentials Bootcamp conducted by LetsUpgrade in collaboration with NSDC and ITM Edutech Training Pvt. Ltd.",
    "logo": "./logo/letsupgrade.webp",
    "certificateImg": "./images/Certifications/LetsUpgrade/sql.webp",
    "credentialLink": "",
    "platforms": ["LetsUpgrade"],
    "language": ["SQL"],
    "category": "Bootcamp",
    "completionYear": "July 2023"
  },
  {
    "name": "Cloud Computing",
    "description": "Gained strong knowledge in Cloud Computing through a 12-week NPTEL online certification course conducted by IIT Kharagpur.",
    "logo": "./logo/nptel.png",
    "certificateImg": "./images/Certifications/Nptel/CloudComputing.webp",
    "credentialLink": "",
    "platforms": ["NPTEL"],
    "language": ["Cloud Computing"],
    "category": "Course",
    "completionYear": "April 2024"
  },
  {
    "name": "Introduction to Database Systems",
    "description": "Gained strong knowledge in database concepts through a 12-week NPTEL online certification course conducted by IIT Madras.",
    "logo": "./logo/nptel.png",
    "certificateImg": "./images/Certifications/Nptel/IntroductiontoDatabaseSystems.webp",
    "credentialLink": "",
    "platforms": ["NPTEL"],
    "language": ["SQL"],
    "category": "Course",
    "completionYear": "April 2023"
  },
  {
    "name": "Programming in Java",
    "description": "Gained strong knowledge in Java programming through a 12-week NPTEL online certification course conducted by IIT Kharagpur.",
    "logo": "./logo/nptel.png",
    "certificateImg": "./images/Certifications/Nptel/Programming-In-Java.webp",
    "credentialLink": "",
    "platforms": ["NPTEL"],
    "language": ["Java"],
    "category": "Course",
    "completionYear": "October 2022"
  },
  {
    "name": "Basics of JavaScript Programming",
    "description": "Successfully completed training on Basics of JavaScript Programming conducted by OpenWeaver.",
    "logo": "./logo/openweaver.png",
    "certificateImg": "./images/Certifications/Openweaver/JavascriptBootcamp.webp",
    "credentialLink": "",
    "platforms": ["OpenWeaver"],
    "language": ["JavaScript"],
    "category": "Training",
    "completionYear": "July 2023"
  },
  {
    "name": "Basics of Python Programming",
    "description": "Successfully completed training on Basics of Python Programming conducted by OpenWeaver.",
    "logo": "./logo/openweaver.png",
    "certificateImg": "./images/Certifications/OpenWeaver/Python.webp",
    "credentialLink": "",
    "platforms": ["OpenWeaver"],
    "language": ["Python"],
    "category": "Training",
    "completionYear": "July 2023"
  },
  {
    "name": "Build your Movie Recommendation System using Pandas",
    "description": "Successfully completed training on building a Movie Recommendation System using Pandas conducted by OpenWeaver.",
    "logo": "./logo/openweaver.png",
    "certificateImg": "./images/Certifications/Openweaver/RecommendationSystem.webp",
    "credentialLink": "",
    "platforms": ["OpenWeaver"],
    "language": ["Python", "Pandas"],
    "category": "Training",
    "completionYear": "July 2023"
  },
  {
    "name": "AI in Data Analysis",
    "description": "Successfully completed the course demonstrating theoretical and practical understanding of AI in Data Analysis.",
    "logo": "./logo/sololearn.svg",
    "certificateImg": "./images/Certifications/SoloLearn/AIinDataAnalysis.webp",
    "credentialLink": "",
    "platforms": ["SoloLearn"],
    "language": ["AI", "Data Analysis"],
    "category": "Course",
    "completionYear": "March 2025"
  },
  {
    "name": "Generative AI in Practice",
    "description": "Successfully completed the course demonstrating theoretical and practical understanding of Generative AI in Practice.",
    "logo": "./logo/sololearn.svg",
    "certificateImg": "./images/Certifications/SoloLearn/GenerativeAIinPractice.webp",
    "credentialLink": "",
    "platforms": ["SoloLearn"],
    "language": ["AI", "Generative AI"],
    "category": "Course",
    "completionYear": "March 2025"
  },
  {
    "name": "Introduction to LLMs",
    "description": "Successfully completed the course demonstrating theoretical and practical understanding of Introduction to LLMs.",
    "logo": "./logo/sololearn.svg",
    "certificateImg": "./images/Certifications/SoloLearn/IntroductiontoLLMs.webp",
    "credentialLink": "",
    "platforms": ["SoloLearn"],
    "language": ["LLM", "AI"],
    "category": "Course",
    "completionYear": "March 2025"
  },
  {
    "name": "Introduction to Python",
    "description": "Successfully completed the course demonstrating theoretical and practical understanding of Introduction to Python.",
    "logo": "./logo/sololearn.svg",
    "certificateImg": "./images/Certifications/SoloLearn/IntroductiontoPython.webp",
    "credentialLink": "",
    "platforms": ["SoloLearn"],
    "language": ["Python"],
    "category": "Course",
    "completionYear": "June 2023"
  },
  {
    "name": "ML for Beginners",
    "description": "Successfully completed the course demonstrating theoretical and practical understanding of Machine Learning for Beginners.",
    "logo": "./logo/sololearn.svg",
    "certificateImg": "./images/Certifications/SoloLearn/MLforBeginners.webp",
    "credentialLink": "",
    "platforms": ["SoloLearn"],
    "language": ["Machine Learning"],
    "category": "Course",
    "completionYear": "March 2025"
  },
  {
    "name": "Prompt Engineering",
    "description": "Successfully completed the course demonstrating theoretical and practical understanding of Prompt Engineering.",
    "logo": "./logo/sololearn.svg",
    "certificateImg": "./images/Certifications/SoloLearn/PromptEngineering.webp",
    "credentialLink": "",
    "platforms": ["SoloLearn"],
    "language": ["AI", "Prompt Engineering"],
    "category": "Course",
    "completionYear": "March 2025"
  },
  {
    "name": "Visualize Your Data",
    "description": "Successfully completed the course demonstrating theoretical and practical understanding of data visualization.",
    "logo": "./logo/sololearn.svg",
    "certificateImg": "./images/Certifications/SoloLearn/VisualizeYourData.webp",
    "credentialLink": "",
    "platforms": ["SoloLearn"],
    "language": ["Data Visualization"],
    "category": "Course",
    "completionYear": "March 2025"
  },
  {
    "name": "Technology Job Simulation",
    "description": "Completed a hands-on technology job simulation covering coding and development tasks as part of Deloitte's virtual experience program.",
    "logo": "./logo/deloitte.png",
    "certificateImg": "./images/Certifications/Deloitte.webp",
    "credentialLink": "",
    "platforms": ["Deloitte"],
    "language": ["HTML", "CSS", "JavaScript"],
    "category": "Virtual Experience",
    "completionYear": "March 2025"
  },
  {
    "name": "Introduction to Data Science",
    "description": "Completed the Introduction to Data Science course by Cisco Networking Academy, gaining foundational knowledge of data analytics and its role in AI and machine learning.",
    "logo": "./logo/Cisco.svg",
    "certificateImg": "./images/Certifications/Cisco.webp",
    "credentialLink": "",
    "platforms": ["Cisco"],
    "language": ["Data Science", "Python"],
    "category": "Course",
    "completionYear": "April 2024"
  },
  {
    "name": "Advanced SQL Programming",
    "description": "Successfully completed a course in Advanced SQL Programming from Mindluster, enhancing skills in database querying and optimization.",
    "logo": "./logo/MindLuster.png",
    "certificateImg": "./images/Certifications/mindLuster-SQL.webp",
    "credentialLink": "",
    "platforms": ["Mindluster"],
    "language": ["SQL"],
    "category": "Course",
    "completionYear": "May 2023"
  },
  {
    "name": "MongoDB Basics",
    "description": "Completed the MongoDB Basics course as part of the ICT Academy Learnathon, learning the essentials of NoSQL databases and MongoDB usage.",
    "logo": "./logo/MongoDB.svg",
    "certificateImg": "./images/Certifications/MongoDB.webp",
    "credentialLink": "",
    "platforms": ["MongoDB"],
    "language": ["MongoDB"],
    "category": "Course",
    "completionYear": "August 2023"
  },
  {
    "name": "Getting Started with AI on Jetson Nano",
    "description": "Demonstrated competency in deploying AI models on edge devices using NVIDIA's Jetson Nano platform.",
    "logo": "./logo/nvidia.svg",
    "certificateImg": "./images/Certifications/nvidia.webp",
    "credentialLink": "",
    "platforms": ["NVIDIA"],
    "language": ["AI", "Edge Computing"],
    "category": "Course",
    "completionYear": "March 2025"
  },
  {
    "name": "PCAP: Programming Essentials in Python",
    "description": "Completed the PCAP: Programming Essentials in Python course, mastering foundational programming concepts, Python 3 syntax, OOP, and file handling.",
    "logo": "./logo/OpenEDG.png",
    "certificateImg": "./images/Certifications/Programming-Esse-certificate.webp",
    "credentialLink": "",
    "platforms": ["Cisco", "Python Institute"],
    "language": ["Python"],
    "category": "Course",
    "completionYear": "May 2024"
  },
  {
    "name": "API 101 using Postman",
    "description": "Participated in the 'API 101 using Postman' event organized by SoarX, gaining insights into the basics of API development and testing.",
    "logo": "./logo/SoarX.png",
    "certificateImg": "./images/Certifications/SoarXApi.webp",
    "credentialLink": "",
    "platforms": ["SoarX", "Postman"],
    "language": ["API", "Postman"],
    "category": "Workshop",
    "completionYear": "April 2024"
  },
  {
    "name": "Masterclass: Building Tech for Scale",
    "description": "Attended an exclusive masterclass by Arun Mahapatro, Site Lead at LinkedIn, on designing scalable data infrastructure and technology systems.",
    "logo": "./logo/Nxtwave.svg",
    "certificateImg": "./images/Certifications/Nxtwave/Building-Tech-Masterclass.png",
    "credentialLink": "",
    "platforms": ["NxtWave"],
    "language": [],
    "category": "Masterclass",
    "completionYear": "September 2023"
  },
  {
    "name": "Data Analytics Mega Workshop",
    "description": "Completed an intensive workshop focused on data analytics and dashboard building using Power BI, Kaggle, and other data tools.",
    "logo": "./logo/Nxtwave.svg",
    "certificateImg": "./images/Certifications/Nxtwave/Data-Analytics-Workshop.png",
    "credentialLink": "",
    "platforms": ["NxtWave"],
    "language": ["Power BI", "Data Analysis"],
    "category": "Workshop",
    "completionYear": "January 2024"
  },
  {
    "name": "Masterclass: Data Science 101",
    "description": "Participated in a foundational data science masterclass by Karthikeya Racharla, Senior Data Scientist at PayPal, covering essential concepts in data science.",
    "logo": "./logo/Nxtwave.svg",
    "certificateImg": "./images/Certifications/Nxtwave/Data-Science-101-Masterclass.jpg",
    "credentialLink": "",
    "platforms": ["NxtWave"],
    "language": ["Python", "Data Science"],
    "category": "Masterclass",
    "completionYear": "August 2023"
  },
  {
    "name": "Masterclass: How to Become a Data Scientist at Microsoft?",
    "description": "Attended an insightful session with Tezan Sahu, Data and Applied Scientist at Microsoft, on the path and skills needed to become a data scientist at Microsoft.",
    "logo": "./logo/Nxtwave.svg",
    "certificateImg": "./images/Certifications/Nxtwave/Data-Scientist-Webinar.png",
    "credentialLink": "",
    "platforms": ["NxtWave"],
    "language": ["Data Science"],
    "category": "Masterclass",
    "completionYear": "June 2024"
  },
  {
    "name": "Generative AI Mega Workshop 2.0",
    "description": "Successfully built a pitch-ready product using 10+ AI tools in the Generative AI Mega Workshop hosted by Tezan Sahu, SDE II at Microsoft.",
    "logo": "./logo/Nxtwave.svg",
    "certificateImg": "./images/Certifications/Nxtwave/GenerativeAI.png",
    "credentialLink": "",
    "platforms": ["NxtWave"],
    "language": ["AI", "Machine Learning"],
    "category": "Workshop",
    "completionYear": "September 2024"
  },

    {
      "name": "NxtCode - 7 Under 7 Challenge 7-Day Milestone",
      "description": "Successfully achieved the 7-day milestone in the NxtCode 7 Under 7 Challenge, demonstrating consistent coding skills and problem-solving commitment.",
            "logo": "./logo/Nxtwave.svg",
      "certificateImg": "./images/Certifications/Nxtwave/NxtCode.png",
      "credentialLink": "",
      "platforms": ["NxtWave"],
      "language": ["Programming"],
      "category": "Achievement",
      "completionYear": "October 2024"
    },
    {
      "name": "DSA CodeVerse Bi-Weekly Contest #8",
      "description": "Ranked 64th in the DSA CodeVerse Bi-Weekly Contest #8, showcasing dedication and improvement in data structures and algorithms.",
            "logo": "./logo/Nxtwave.svg",
      "certificateImg": "./images/Certifications/Nxtwave/NxtwaveCodingCompetition.png",
      "credentialLink": "",
      "platforms": ["NxtWave"],
      "language": ["Data Structures", "Algorithms"],
      "category": "Contest",
      "completionYear": "April 2025"
    },
    {
      "name": "Masterclass: Project Management 101",
      "description": "Attended a masterclass by Vinay Nandina, Project Manager at Microsoft, covering the fundamentals of effective project management.",
            "logo": "./logo/Nxtwave.svg",
      "certificateImg": "./images/Certifications/Nxtwave/Project-Management-101-Workshop.png",
      "credentialLink": "",
      "platforms": ["NxtWave"],
      "language": ["Project Management"],
      "category": "Masterclass",
      "completionYear": "July 2024"
    },
    {
      "name": "Masterclass: Becoming a Security Engineer",
      "description": "Participated in a masterclass by Sandeep Bhandari, Security Engineer at Amazon Ads, focused on the career path and skills for security engineering.",
            "logo": "./logo/Nxtwave.svg",
      "certificateImg": "./images/Certifications/Nxtwave/Security-Engineer-Masterclass.png",
      "credentialLink": "",
      "platforms": ["NxtWave"],
      "language": ["Cybersecurity"],
      "category": "Masterclass",
      "completionYear": "November 2023"
    },
    {
      "name": "UI/UX Mega Workshop",
      "description": "Completed a UI/UX mega workshop hosted by Aman Maheshwari, Head of Product Design at NxtWave, successfully redesigning an app using Figma.",
            "logo": "./logo/Nxtwave.svg",
      "certificateImg": "./images/Certifications/Nxtwave/UIUX.png",
      "credentialLink": "",
      "platforms": ["NxtWave"],
      "language": ["UI/UX", "Figma"],
      "category": "Workshop",
      "completionYear": "December 2024"
    },
    {
      "name": "XPM 4.0 Fundamentals - Exponential Performance Mindset",
      "description": "Completed the XPM 4.0 Fundamentals course focusing on personal identity, integrity, goal setting, and achieving an exponential performance mindset.",
            "logo": "./logo/Nxtwave.svg",
      "certificateImg": "",
      "credentialLink": "https://certificates.ccbp.in/academy/xpm-4-0-fundamentals?id=FXHBBEOQGM",
      "platforms": ["NxtWave"],
      "language": ["Personal Development"],
      "category": "Course",
      "completionYear": "January 2024"
    },
    {
      "name": "DSA CodeVerse Bi-Weekly Contest #9",
      "description": "Ranked 46th in the DSA CodeVerse Bi-Weekly Contest #9, demonstrating exceptional problem-solving skills and commitment to continuous learning.",
            "logo": "./logo/Nxtwave.svg",
      "certificateImg": "./images/Certifications/Nxtwave/NxtwaveCoding.png",
      "credentialLink": "",
      "platforms": ["NxtWave"],
      "language": ["Data Structures", "Algorithms"],
      "category": "Contest",
      "completionYear": "April 2025"
    }


];

export default certifications;
